ln -sv ~/code/timtyrrell/dotfiles/coc-settings.json ~/.config/nvim/coc-settings.json
ln -sv ~/code/timtyrrell/dotfiles/init.vim ~/.config/nvim/init.vim
ln -sv ~/code/timtyrrell/dotfiles/mini.vim ~/.config/nvim/mini.vim
ln -sv ~/code/timtyrrell/dotfiles/.zshrc ~/.zshrc
ln -sv ~/code/timtyrrell/dotfiles/.tmux.conf ~/.tmux.conf
ln -sv ~/code/timtyrrell/dotfiles/.gitconfig ~/.gitconfig
ln -sv ~/code/timtyrrell/dotfiles/.gitconfig.local ~/.gitconfig.local
ln -sv ~/code/timtyrrell/dotfiles/ultisnips ~/.config/coc/ultisnips
ln -sv ~/code/timtyrrell/dotfiles/kitty.conf ~/.config/kitty/kitty.conf
ln -sv ~/code/timtyrrell/dotfiles/bin/preview_file_or_folder.sh ~/bin/preview_file_or_folder.sh
ln -sv ~/code/timtyrrell/dotfiles/bin/tmux-spotify-info ~/bin/tmux-spotify-info
ln -sv ~/code/timtyrrell/dotfiles/bin/tmux_chooser ~/bin/tmux_chooser
ln -sv ~/code/timtyrrell/dotfiles/bin/truecolor-test ~/bin/truecolor-test
ln -sv ~/code/timtyrrell/dotfiles/Brewfile ~/.Brewfile
ln -sv ~/code/timtyrrell/dotfiles/KittyApprentice.conf ~/.config/kitty/themes/Apprentice.conf
ln -sv ~/code/timtyrrell/dotfiles/pre-commit ~/code/timtyrrell/dotfiles/.git/hooks/pre-commit
ln -sv ~/code/timtyrrell/dotfiles/tidy_config.txt ~/.config/tidy_config.txt
